name: Azure Web App Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Bicep
      run: |
        az bicep install

    - name: Create Resource Group
      run: |
        az group create \
          --name ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --location ${{ secrets.AZURE_LOCATION }}

    - name: Deploy Web App and Service Plan
      run: |
        az deployment group create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --template-file ./bicep/main.bicep \
          --parameters webAppName='ofdna-web-dev' \
                       appServicePlanName='ofdna-app-service-plan' \
                       location='${{ secrets.AZURE_LOCATION }}'
