name: Azure Web App Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Dev
    permissions: 
      id-token: write
      contents: read


    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}  
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}  
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up Bicep
      run: |
        az bicep install

    - name: Create Resource Group
      run: |
        az group create \
          --name ${{ secrets.AZURE_RESOURCE_GROUP }} 
          --location ${{ secrets.AZURE_LOCATION }}

    
    - name: Deploy Web App and Service Plan
      run: |
        az deployment group create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --template-file ./bicep/main.bicep \
          --parameters webAppName='ofdna-web-dev2' \
                       appServicePlanName='ofdna-app-service-plan2' \
                       location='${{ secrets.AZURE_LOCATION }}'
